name: Github Pages Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: yarn install

      - name: Upgrade
        run: yarn upgrade

      - name: Build
        run: yarn build

      - name: Deploy
        run: yarn run deploy
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"